/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sistemadevuelos.BusquedaVuelos;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Font;
import java.awt.GridLayout;
import java.util.Random;
import javax.swing.BoxLayout;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.border.EmptyBorder;
import sistemadevuelos.FondoPanel;
import sistemadevuelos.Home.Inicio;
import sistemadevuelos.InicioSesion.FlightDetails;
import sistemadevuelos.InicioSesion.IniciarSesion;

/**
 *
 * @author ACER
 */
public class DetalleVuelo extends javax.swing.JFrame {
    //para el fondo
    FondoPanel fondo2 = new FondoPanel();
    /**
     * Creates new form DetalleVuelo
     */
     public DetalleVuelo(Object origen, Object destino, Object fechaDeIda, Object pasajeros, Object precio, Object horarioSalida, Object horarioLlegada) {
        // Para el fondo
    this.setContentPane(fondo2);
    
    initComponents();
    // Centrar el formulario
    this.setLocationRelativeTo(this);
    
    // Generar un número de vuelo aleatorio
    Random random = new Random();
    int numeroDeVuelo = 1000 + random.nextInt(9000); // Número de vuelo entre 1000 y 9999

    // Generar una aerolínea aleatoria
    String[] aerolineas = {"Flybondi", "Aerolíneas Argentinas", "JetSmart", "Aerolínea D", "Aerolínea E"};
    String aerolinea = aerolineas[random.nextInt(aerolineas.length)];

    // Configurar los labels con la información recibida y generada aleatoriamente
    NumeroDeVuelo.setText("Número de vuelo: " + numeroDeVuelo);
    Aerolinea.setText("Aerolínea: " + aerolinea);
    Origen.setText("Origen: " + origen.toString());
    Destino.setText("Destino: " + destino.toString());
    FechaDePartida.setText("Fecha de partida: " + fechaDeIda.toString());
    Pasajes.setText("Pasajes: " + pasajeros.toString());
    Precio.setText("Precio: " + precio.toString());
    HorarioDeSalida.setText("Horario de salida: " + horarioSalida.toString());
    HorarioDeLlegada.setText("Horario de llegada: " + horarioLlegada.toString());
    Puerta.setText("Puerta: Sin definir");
    
    // Guardar la cantidad de pasajes
    FlightDetails.getInstance().setCantidadPasajes(Integer.parseInt(pasajeros.toString()));
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new FondoPanel();
        Inicio_btn = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        Origen = new javax.swing.JLabel();
        FechaDePartida = new javax.swing.JLabel();
        Pasajes = new javax.swing.JLabel();
        Precio = new javax.swing.JLabel();
        Destino = new javax.swing.JLabel();
        HorarioDeSalida = new javax.swing.JLabel();
        HorarioDeLlegada = new javax.swing.JLabel();
        NumeroDeVuelo = new javax.swing.JLabel();
        Puerta = new javax.swing.JLabel();
        continuar_btn = new javax.swing.JButton();
        Aerolinea = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setPreferredSize(new java.awt.Dimension(1260, 986));

        Inicio_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistemadevuelos/Imagenes/VOLANDO.png"))); // NOI18N
        Inicio_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Inicio_btnMouseClicked(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setPreferredSize(new java.awt.Dimension(1000, 847));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel1.setText("Detalles del vuelo:");

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        Origen.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Origen.setText("Origen:");

        FechaDePartida.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        FechaDePartida.setText("Fecha de partida:");

        Pasajes.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Pasajes.setText("Pasajes:");

        Precio.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Precio.setText("Precio:");

        Destino.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Destino.setText("Destino:");

        HorarioDeSalida.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        HorarioDeSalida.setText("Horario de salida:");

        HorarioDeLlegada.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        HorarioDeLlegada.setText("Horario de llegada:");

        NumeroDeVuelo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        NumeroDeVuelo.setText("Número de vuelo:");

        Puerta.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Puerta.setText("Puerta:");

        continuar_btn.setBackground(new java.awt.Color(0, 0, 0));
        continuar_btn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        continuar_btn.setForeground(new java.awt.Color(255, 255, 255));
        continuar_btn.setText("Continuar con la compra");
        continuar_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                continuar_btnActionPerformed(evt);
            }
        });

        Aerolinea.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Aerolinea.setText("Aerolinea:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Destino)
                            .addComponent(FechaDePartida)
                            .addComponent(Origen)
                            .addComponent(Pasajes)
                            .addComponent(Precio)
                            .addComponent(HorarioDeSalida)
                            .addComponent(HorarioDeLlegada)
                            .addComponent(NumeroDeVuelo))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Puerta)
                            .addComponent(Aerolinea))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(continuar_btn)
                        .addGap(62, 62, 62))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(230, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 660, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(206, 206, 206))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(389, 389, 389))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Origen)
                .addGap(46, 46, 46)
                .addComponent(Destino, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(FechaDePartida, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(Pasajes, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(Precio, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(HorarioDeSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(HorarioDeLlegada, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(NumeroDeVuelo, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(continuar_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(Puerta, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                        .addComponent(Aerolinea, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39))))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Inicio_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1096, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(83, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(Inicio_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 878, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1271, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Inicio_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Inicio_btnMouseClicked
        //Para volver al inicio haciendo click en el logo
        Inicio inicio = new Inicio();

        // Hacer visible el JFrame Busqueda
        inicio.setVisible(true);

        // Cerrar el JFrame actual (Inicio)
        this.dispose();
    }//GEN-LAST:event_Inicio_btnMouseClicked

    private void continuar_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_continuar_btnActionPerformed
       //Para volver al inicio haciendo click en el logo
        IniciarSesion inicio = new IniciarSesion();

        // Hacer visible el JFrame Busqueda
        inicio.setVisible(true);

        // Cerrar el JFrame actual (Inicio)
        this.dispose();
    }//GEN-LAST:event_continuar_btnActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Aerolinea;
    private javax.swing.JLabel Destino;
    private javax.swing.JLabel FechaDePartida;
    private javax.swing.JLabel HorarioDeLlegada;
    private javax.swing.JLabel HorarioDeSalida;
    private javax.swing.JLabel Inicio_btn;
    private javax.swing.JLabel NumeroDeVuelo;
    private javax.swing.JLabel Origen;
    private javax.swing.JLabel Pasajes;
    private javax.swing.JLabel Precio;
    private javax.swing.JLabel Puerta;
    private javax.swing.JButton continuar_btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
