/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sistemadevuelos.ReservaPasaje;

import com.mysql.jdbc.Connection;
import com.mysql.jdbc.PreparedStatement;
import sistemadevuelos.conexion.ConexionDB;
import java.sql.ResultSet;
import java.sql.SQLException;
import sistemadevuelos.InicioSesion.SessionManager;


public class PagoSatisfactorio extends javax.swing.JFrame {

    public PagoSatisfactorio() {
         initComponents();
         getContentPane().setBackground(java.awt.Color.WHITE);
        // Obtener el ID del usuario actual desde SessionManager
        int idUsuario = SessionManager.getIdUsuarioActual();
        // Obtener el ID del pasajero asociado
        int idPasajero = obtenerIdPasajero(idUsuario);
        // Obtener y mostrar el código de reserva
        if (idPasajero != -1) {
            String codigoReserva = obtenerCodigoReserva(idPasajero);
            if (codigoReserva != null) {
                codigoReservaLabel.setText("Su código de reserva es: " + codigoReserva);
            } else {
                codigoReservaLabel.setText("No se encontró un código de reserva para el ID de pasajero: " + idPasajero);
            }
        } else {
            codigoReservaLabel.setText("No se encontró el ID del pasajero para el usuario: " + idUsuario);
        }
    }

    private int obtenerIdPasajero(int idUsuario) {
        int idPasajero = -1; // Valor predeterminado si no se encuentra el pasajero
        ConexionDB db = new ConexionDB();
        try (Connection conn = (Connection) db.conectar()) {
            if (conn != null) {
                String sql = "SELECT id FROM pasajeros WHERE usuario_id = ?";
                try (PreparedStatement pstmt = (PreparedStatement) conn.prepareStatement(sql)) {
                    pstmt.setInt(1, idUsuario);
                    try (ResultSet rs = pstmt.executeQuery()) {
                        if (rs.next()) {
                            idPasajero = rs.getInt("id");
                        } else {
                            System.out.println("No se encontró el pasajero para el usuario: " + idUsuario);
                        }
                    }
                }
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return idPasajero;
    }

    private String obtenerCodigoReserva(int idPasajero) {
        String codigoReserva = null;
        ConexionDB db = new ConexionDB();
        try (Connection conn = (Connection) db.conectar()) {
            if (conn != null) {
                String sql = "SELECT codigo_reserva FROM pasajeros WHERE id = ?";
                try (PreparedStatement pstmt = (PreparedStatement) conn.prepareStatement(sql)) {
                    pstmt.setInt(1, idPasajero);
                    try (ResultSet rs = pstmt.executeQuery()) {
                        if (rs.next()) {
                            codigoReserva = rs.getString("codigo_reserva");
                        } else {
                            System.out.println("No se encontró el código de reserva para el ID de pasajero: " + idPasajero);
                        }
                    }
                }
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return codigoReserva;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        codigoReservaLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("¡SU PAGO SE HA REALIZADO SATISFACTORIAMENTE!");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        jLabel2.setText("Disfrute su proximo destino, le desea:");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistemadevuelos/Imagenes/VOLANDO.png"))); // NOI18N

        codigoReservaLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 73, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(68, 68, 68))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(115, 115, 115)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(133, 133, 133)
                            .addComponent(codigoReservaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(85, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(codigoReservaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel codigoReservaLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
