/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sistemadevuelos.ReservaPasaje;

import java.util.Random;
import sistemadevuelos.InicioSesion.FlightDetails;

/**
 *
 * @author ACER
 */
public class Ticket extends javax.swing.JFrame {

    /**
     * Creates new form Ticket
     */
    public Ticket() {
        initComponents();
  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        NumeroDeVuelo = new javax.swing.JLabel();
        Origen = new javax.swing.JLabel();
        Destino = new javax.swing.JLabel();
        FechaDePartida = new javax.swing.JLabel();
        Pasajes = new javax.swing.JLabel();
        Asientos = new javax.swing.JLabel();
        HorarioDeSalida = new javax.swing.JLabel();
        HorarioDeLlegada = new javax.swing.JLabel();
        Puerta = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 28)); // NOI18N
        jLabel1.setText("Ticket");

        NumeroDeVuelo.setText("Numero de vuelo: ");

        Origen.setText("Origen:");

        Destino.setText("Destino:");

        FechaDePartida.setText("Fecha de partida:");

        Pasajes.setText("Pasajes:");

        Asientos.setText("Asientos:");

        HorarioDeSalida.setText("Horario de salida:");

        HorarioDeLlegada.setText("Horario de llegada:");

        Puerta.setText("Puerta:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(195, 195, 195)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Origen)
                            .addComponent(NumeroDeVuelo)
                            .addComponent(Destino)
                            .addComponent(FechaDePartida)
                            .addComponent(Pasajes)
                            .addComponent(Asientos)
                            .addComponent(HorarioDeSalida)
                            .addComponent(HorarioDeLlegada)
                            .addComponent(Puerta))))
                .addContainerGap(223, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(NumeroDeVuelo)
                .addGap(28, 28, 28)
                .addComponent(Origen)
                .addGap(28, 28, 28)
                .addComponent(Destino)
                .addGap(27, 27, 27)
                .addComponent(FechaDePartida)
                .addGap(29, 29, 29)
                .addComponent(Pasajes)
                .addGap(27, 27, 27)
                .addComponent(Asientos)
                .addGap(30, 30, 30)
                .addComponent(HorarioDeSalida)
                .addGap(31, 31, 31)
                .addComponent(HorarioDeLlegada)
                .addGap(32, 32, 32)
                .addComponent(Puerta)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Asientos;
    private javax.swing.JLabel Destino;
    private javax.swing.JLabel FechaDePartida;
    private javax.swing.JLabel HorarioDeLlegada;
    private javax.swing.JLabel HorarioDeSalida;
    private javax.swing.JLabel NumeroDeVuelo;
    private javax.swing.JLabel Origen;
    private javax.swing.JLabel Pasajes;
    private javax.swing.JLabel Puerta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
